type ReportStatus = "processing" | "completed" | "error";

type ReportPhase =
  | "queued"
  | "reading_documents"
  | "analyzing_data"
  | "generating_charts"
  | "drafting_report"
  | "completed"
  | "error";

interface ReportConfig {
  scope: "summary" | "operational" | "strategic";
  detailLevel: "low" | "medium" | "high";
  language: "es" | "en";
  exportFormat: "docx" | "pdf" | "md";
  caseId?: string;
}

interface ReportOrchestrationMeta {
  caseId: string;
  usedModelId: string;
  usedProviderId: string;
  usedPromptVersion: number;
  traceId: string;
  attempts: Array<{ modelId: string; providerId?: string; ok: boolean; error?: string }>;
}

interface ReportFile {
  name: string;
  size: number;
  mimeType: string;
}

interface ReportFileSource {
  type: "file";
  file: ReportFile;
}

interface ReportTextSource {
  type: "text";
  title: string;
  content: string;
  format: "md";
}

type ReportSource = ReportFileSource | ReportTextSource;

interface InternalReport {
  id: string;
  userId: string;
  title: string;
  status: ReportStatus;
  phase: ReportPhase;
  progress: number;
  createdAt: Date;
  updatedAt: Date;
  startedAt: Date;
  config: ReportConfig;
  sources: ReportSource[];
  content: string;
  changeLog: string[];
  orchestration?: ReportOrchestrationMeta;
  errorMessage?: string;
}

interface CreateReportInput {
  title: string;
  config: ReportConfig;
  sources: ReportSource[];
  orchestration?: ReportOrchestrationMeta;
}

const reportsStore = new Map<string, InternalReport>();

const PHASES = [
  { maxSeconds: 4, phase: "reading_documents", progress: 22 },
  { maxSeconds: 9, phase: "analyzing_data", progress: 48 },
  { maxSeconds: 14, phase: "generating_charts", progress: 74 },
  { maxSeconds: 20, phase: "drafting_report", progress: 92 },
] as const;

function now() {
  return new Date();
}

function makeId() {
  return `rio_${crypto.randomUUID()}`;
}

function toJSON(report: InternalReport) {
  return {
    id: report.id,
    title: report.title,
    status: report.status,
    phase: report.phase,
    progress: report.progress,
    createdAt: report.createdAt.toISOString(),
    updatedAt: report.updatedAt.toISOString(),
    config: report.config,
    sources: report.sources,
    content: report.content,
    changeLog: report.changeLog,
    orchestration: report.orchestration,
    errorMessage: report.errorMessage,
  };
}

function buildFinalContent(report: InternalReport) {
  const fileSources = report.sources.filter(
    (source): source is ReportFileSource => source.type === "file"
  );
  const textSources = report.sources.filter(
    (source): source is ReportTextSource => source.type === "text"
  );
  const totalBytes = fileSources.reduce((acc, source) => acc + source.file.size, 0);
  const totalMb = (totalBytes / (1024 * 1024)).toFixed(2);
  const totalTextChars = textSources.reduce((acc, source) => acc + source.content.length, 0);
  const sourceBreakdown = [
    `- Total sources: ${report.sources.length}`,
    `- Files processed: ${fileSources.length}`,
    `- Markdown text inputs: ${textSources.length}`,
    `- Total payload from files: ${totalMb} MB`,
    `- Total markdown characters: ${totalTextChars}`,
  ];

  return [
    `# ${report.title}`,
    "",
    "## Executive Summary",
    "The AI orchestrator consolidated the uploaded evidence and generated a guided report.",
    "",
    "## Scope",
    `- Scope: ${report.config.scope}`,
    `- Detail level: ${report.config.detailLevel}`,
    `- Language: ${report.config.language}`,
    `- Case ID: ${report.config.caseId ?? "orchestrator.default"}`,
    ...sourceBreakdown,
    ...(report.orchestration
      ? [
          `- Model used: ${report.orchestration.usedModelId}`,
          `- Provider used: ${report.orchestration.usedProviderId}`,
          `- Prompt version: v${report.orchestration.usedPromptVersion}`,
          `- Trace ID: ${report.orchestration.traceId}`,
        ]
      : []),
    "",
    "## Key Findings",
    "1. Source documents were normalized and grouped by topic.",
    "2. Quantitative signals were transformed into chart-friendly datasets.",
    "3. Narrative sections were drafted with references to source snippets.",
    "",
    "## Recommendations",
    "- Validate critical assumptions before external distribution.",
    "- Keep this report as baseline for upcoming iteration.",
    "",
    "## Traceability",
    "This artifact was generated by AI report orchestration in beta mode.",
  ].join("\n");
}

export function createReport(userId: string, input: CreateReportInput) {
  const createdAt = now();

  const report: InternalReport = {
    id: makeId(),
    userId,
    title: input.title,
    status: "processing",
    phase: "queued",
    progress: 5,
    createdAt,
    updatedAt: createdAt,
    startedAt: createdAt,
    config: input.config,
    sources: input.sources,
    content: "",
    orchestration: input.orchestration,
    changeLog: [
      "Report created",
      "Input sources received",
      ...(input.orchestration
        ? [
            `Model selected: ${input.orchestration.usedModelId}`,
            `Provider selected: ${input.orchestration.usedProviderId}`,
          ]
        : []),
      "Pipeline enqueued",
    ],
  };

  reportsStore.set(report.id, report);
  return toJSON(report);
}

export function listReports(userId: string) {
  return Array.from(reportsStore.values())
    .filter((report) => report.userId === userId)
    .map((report) => advanceAndSerialize(report))
    .sort((a, b) => +new Date(b.createdAt) - +new Date(a.createdAt));
}

export function getReport(userId: string, reportId: string) {
  const report = reportsStore.get(reportId);
  if (!report || report.userId !== userId) {
    return null;
  }

  return advanceAndSerialize(report);
}

export function deleteReport(userId: string, reportId: string) {
  const report = reportsStore.get(reportId);
  if (!report || report.userId !== userId) {
    return false;
  }

  reportsStore.delete(reportId);
  return true;
}

export function updateReportTitle(userId: string, reportId: string, title: string) {
  const report = reportsStore.get(reportId);
  if (!report || report.userId !== userId) {
    return null;
  }

  report.title = title;
  report.updatedAt = now();
  report.changeLog.unshift("Title updated from dashboard");

  return toJSON(report);
}

export function createExportToken(userId: string, reportId: string, format: "docx" | "pdf" | "md") {
  const report = reportsStore.get(reportId);
  if (!report || report.userId !== userId) {
    return null;
  }

  const safeName = report.title.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  return {
    fileName: `${safeName || "report"}.${format}`,
    downloadUrl: `https://example.invalid/exports/${report.id}.${format}`,
    generatedAt: new Date().toISOString(),
  };
}

function advanceAndSerialize(report: InternalReport) {
  if (report.status !== "processing") {
    return toJSON(report);
  }

  const elapsed = Math.floor((Date.now() - report.startedAt.getTime()) / 1000);

  for (const phase of PHASES) {
    if (elapsed < phase.maxSeconds) {
      report.phase = phase.phase;
      report.progress = phase.progress;
      report.updatedAt = now();
      return toJSON(report);
    }
  }

  report.status = "completed";
  report.phase = "completed";
  report.progress = 100;
  report.content = buildFinalContent(report);
  report.updatedAt = now();
  report.changeLog.unshift("Draft exported to editable report model");
  report.changeLog.unshift("Charts generated and embedded");
  report.changeLog.unshift("Data analysis completed");

  return toJSON(report);
}
